---

time:
  startTime: 0.0
  endTime: 0.15
  dt: 0.001

constants:
  planckConstant: 1.0
  mass: 1.0
  alfa: 2.0
  besselResolutionExpotential: 16

domain:
  period: 3
  resolutionExpotential: 8

functions:
  potential: "default"
  waveFunction: "default"

filePaths:
  nodesFile: "nodes.txt"
  hdf5JavaFile: "hdf5/quancalculations.h5"
  hdf5PythonFile: "../hdf5/quancalculations.h5"
