time:
  startTime: 0
  endTime: 1
  dt: 0.001

constants:
  planckConstant: 1
  mass: 1
  alfa: 1.2

domain:
  period: 3
  resolutionExpotential: 7

functions:
  potential: "default"
  waveFunction: "default"

nodesFileName: "nodes.txt"
hdf5FilePath: "hdf5/myfile.h5"