time:
  startTime: 0
  endTime: 1
  dt: 0.001

constants:
  planckConstant: 1
  mass: 1
  alfa: 1.2
  besselResolutionExpotential: 10

domain:
  period: 3
  resolutionExpotential: 12

functions:
  potential: "default"
  waveFunction: "default"

nodesFileName: "nodes.txt"
hdf5FilePath: "hdf5/myfile.h5"
# File path to HDF5 file relative to the python folder
hdf5PythonFolderFilePath: "../hdf5/myfile.h5"