---

time:
  startTime: 0
  endTime: 1
  dt: 0.001

constants:
  planckConstant: 1
  mass: 1
  alfa: 1.2
  besselResolutionExpotential: 10

domain:
  period: 3
  resolutionExpotential: 12

functions:
  potential: "default"
  waveFunction: "default"

filePaths:
  nodesFile: "nodes.txt"
  hdf5JavaFile: "hdf5/quancalculations.h5"
  hdf5PythonFile: "../hdf5/quancalculations.h5"
