---

time:
  startTime: 0.0
  endTime: 0.05
  dt: 0.01

constants:
  planckConstant: 1.0
  mass: 1.0
  alfa: 1.4
  besselResolutionExpotential: 16

domain:
  period: 3
  resolutionExpotential: 12

functions:
  potential: "default"
  waveFunction: "default"

filePaths:
  nodesFile: "nodes.txt"
  hdf5JavaFile: "hdf5/quancalculations.h5"
  hdf5PythonFile: "../hdf5/quancalculations.h5"
